FROM nvidia/cuda:12.4.0-runtime-ubuntu22.04
LABEL maintainer="disi-unibo-nlp"

# Zero interaction (default answers to all questions)
ENV DEBIAN_FRONTEND=noninteractive

# Set work directory
WORKDIR /

# Install general-purpose dependencies
RUN apt-get update -y && \
    apt-get install -y curl \
    git \
    bash \
    nano \
    wget \
    python3.9 \
    python3-pip && \
    apt-get autoremove -y && \
    apt-get clean -y && \
    rm -rf /var/lib/apt/lists/*


# Copy the requirements file into the container at /workspace
COPY requirements_base.txt .
COPY requirements_langchain.txt .
COPY requirements_milvus.txt .
COPY requirements_fastchat.txt .


# Install dependencies from requirements.txt
RUN pip3 install --no-cache-dir -r requirements_base.txt
RUN pip3 install --no-cache-dir -r requirements_langchain.txt
RUN pip3 install --no-cache-dir -r requirements_milvus.txt
RUN pip3 install --no-cache-dir -r requirements_fastchat.txt

#RUN pip3 install flash_attn==2.5.8--no-build-isolation


# Milvus
EXPOSE 19530

# FastChat
EXPOSE 7860
ENV GRADIO_SERVER_NAME="0.0.0.0"

# Back to default frontend
ENV DEBIAN_FRONTEND=dialog